spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/deneme1
    username: postgres
    password: 123456789
    hikari:
      maximum-pool-size: 2
      idle-timeout: 15000
      connection-timeout: 20000
      minimum-idle: 2
      max-lifetime: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      org:
        hibernate:
          format_sql: false