spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    username: root
    url: jdbc:mysql://localhost:3306/animals

    security:
      user:
        name: usman
        password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



hibernate:
  dialect=org:
    hibernate:
      dialect:
        MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect
#    mysql database