spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456789
    username: root
    url: jdbc:mysql://localhost:3306/form

    security:
      user:
        name: usman
        password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



hibernate:
  cache:
    region:
      factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
    use_second_level_cache: true
  dialect=org:
    hibernate:
      dialect:
        MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect
#    mysql database